const sidebars = {
  mainSidebar: [
    {
      type: "category",
      label: "Docs Project",
      link: {
        type: "doc",
        id: "index",
      },
      items: [
        {
          type: "autogenerated",
          dirName: "docs",
        },
      ],
    },

    { type: "html", value: "<hr />" },

    {
      type: "category",
      label: "Python Project",
      collapsible: false,
      link: {
        type: "doc",
        id: "python/index",
      },
      items: [],
    },

    { type: "html", value: "<hr />" },

    {
      type: "category",
      label: "API Project",
      collapsible: false,
      link: {
        type: "doc",
        id: "api/index",
      },
      items: [],
    },
  ],
};

export default sidebars;
